server:
  port: 8083

spring:
  application:
    name: resource-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?ApplicationName=ResourceService&currentSchema=resource_service_db
    username: postgres
    password: 112121
    driver-class-name: org.postgresql.Driver

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

